# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
I18n.reload!
# 30.times do
#     Answergroup.create!([{
#         qcd_id: 3,
#         group: true,
#         answer: {
#             "1"=>"#{Faker::RickAndMorty.quote}", 
#             "2"=>"#{Faker::Number.between(1, 5)}", 
#             "3"=>"#{Faker::Number.between(0, 3)}", 
#             "13"=>"#{Faker::Name.Promedioqcd}", 
#             "14"=>"#{Faker::Name.SiONo}", 
#             "15"=>"#{Faker::Number.between(1, 4)}", 
#             "16"=>"#{Faker::Number.between(1, 4)}", 
#             "17"=>"#{Faker::Number.between(1, 4)}",  
#             "18"=>"#{Faker::Number.between(1, 4)}",  
#             "19"=>"#{Faker::Number.between(1, 4)}",  
#             "20"=>"#{Faker::Number.between(1, 4)}",  
#             "21"=>"#{Faker::Number.between(1, 4)}",  
#             "22"=>"#{Faker::Number.between(1, 4)}",  
#             "23"=>"#{Faker::Number.between(1, 4)}",  
#             "24"=>"#{Faker::Number.between(1, 4)}"
#         }.to_json
#     }])
# end

# 30.times do
#     Answergroup.create!([{
#         qcd_id: 3,
#         group: false,
#         answer: {
#             "31"=>"#{Faker::RickAndMorty.quote}", 
#             "32"=>"#{Faker::RickAndMorty.quote}",  
#             "33"=>"#{Faker::Number.between(1, 9)}", 
#             "34"=>"#{Faker::Number.between(1, 9)}", 
#             "35"=>"#{Faker::RickAndMorty.quote}", 
#         }.to_json
#     }])
# end

Answergroup.create!([{
        qcd_id: 102,
        group: true,
        answer: {
            "1"=>"Bien", 
            "2"=>"4", 
            "3"=>"3", 
            "4"=>"2", 
            "5"=>"2", 
            "6"=>"2",
            "13"=>"Entre 3,95 y 5,00", 
            "14"=>"No", 
            "15"=>"1", 
            "16"=>"1", 
            "17"=>"2",  
            "18"=>"1",  
            "19"=>"1",  
            "20"=>"1",  
            "21"=>"1",  
            "22"=>"1",  
            "23"=>"2",  
            "24"=>"1",
            "25"=>"5",
            "26"=>"Esta asignatura es pertinente para mi formación profesional debido a que forja mis maneras de escribir, mi forma de comunicarme y de expresar a traves de las palabras a otras personas"
        }.to_json
    },{
        qcd_id: 102,
        group: true,
        answer: {
            "1"=>"aprendi de todo y fue muy util", 
            "2"=>"5", 
            "3"=>"3", 
            "4"=>"3", 
            "5"=>"3", 
            "6"=>"3",
            "13"=>"Entre 3,25 y 3,94", 
            "14"=>"No", 
            "15"=>"4", 
            "16"=>"4", 
            "17"=>"4",  
            "18"=>"4",  
            "19"=>"4",  
            "20"=>"4",  
            "21"=>"4",  
            "22"=>"4",  
            "23"=>"4",  
            "24"=>"4",
            "25"=>"5",
            "26"=>"depende de todo"
        }.to_json
    },{
        qcd_id: 102,
        group: true,
        answer: {
            "1"=>"Estoy satisfecho con el contenido y el docente", 
            "2"=>"4", 
            "3"=>"3", 
            "4"=>"3", 
            "5"=>"2", 
            "6"=>"3",
            "13"=>"Entre 3,95 y 5,00", 
            "14"=>"No", 
            "15"=>"4", 
            "16"=>"4", 
            "17"=>"3",  
            "18"=>"4",  
            "19"=>"3",  
            "20"=>"4",  
            "21"=>"3",  
            "22"=>"3",  
            "23"=>"4",  
            "24"=>"4",
            "25"=>"5",
            "26"=>"Es un escalón más en nuestra formación como periodistas integrales"
        }.to_json
    },{
        qcd_id: 102,
        group: true,
        answer: {
            "1"=>"Satisfecha", 
            "2"=>"4", 
            "3"=>"2", 
            "4"=>"2", 
            "5"=>"2", 
            "6"=>"2",
            "13"=>"Entre 3,25 y 3,94", 
            "14"=>"No", 
            "15"=>"3", 
            "16"=>"3", 
            "17"=>"3",  
            "18"=>"3",  
            "19"=>"2",  
            "20"=>"3",  
            "21"=>"2",  
            "22"=>"4",  
            "23"=>"3",  
            "24"=>"3",
            "25"=>"3",
            "26"=>"Esta asignatura me aporta pero no es muy pertinente para mi carrera no por que no me agrade si no por que no me gusta el periodismo y me gustaría desempeñarme en un cargo diferente."
        }.to_json
    },{
        qcd_id: 102,
        group: true,
        answer: {
            "1"=>"me parece normal", 
            "2"=>"3", 
            "3"=>"2", 
            "4"=>"2", 
            "5"=>"2", 
            "6"=>"3",
            "13"=>"Entre 3,95 y 5,00", 
            "14"=>"No", 
            "15"=>"2", 
            "16"=>"3", 
            "17"=>"3",  
            "18"=>"3",  
            "19"=>"1",  
            "20"=>"1",  
            "21"=>"2",  
            "22"=>"3",  
            "23"=>"3",  
            "24"=>"3",
            "25"=>"4",
            "26"=>"porque es obvio, se necesita aprender a escribir periodismo para ser un buen comunicador y periodista......"
        }.to_json
    },{
        qcd_id: 102,
        group: true,
        answer: {
            "1"=>"Es sin duda la mejor clase de mi semestre", 
            "2"=>"5", 
            "3"=>"3", 
            "4"=>"3", 
            "5"=>"3", 
            "6"=>"3",
            "13"=>"Entre 3,95 y 5,00", 
            "14"=>"Si", 
            "15"=>"4", 
            "16"=>"4", 
            "17"=>"4",  
            "18"=>"3",  
            "19"=>"3",  
            "20"=>"4",  
            "21"=>"4",  
            "22"=>"4",  
            "23"=>"4",  
            "24"=>"4",
            "25"=>"5",
            "26"=>"El periodismo es el oficio para el que nos formamos. Es necesario y debe impartirse rigurosamente."
        }.to_json
    },{
        qcd_id: 102,
        group: true,
        answer: {
            "1"=>"Muy satisfecho", 
            "2"=>"5", 
            "3"=>"3", 
            "4"=>"3", 
            "5"=>"3", 
            "6"=>"3",
            "13"=>"Entre 3,25 y 3,94", 
            "14"=>"No", 
            "15"=>"3", 
            "16"=>"3", 
            "17"=>"3",  
            "18"=>"3",  
            "19"=>"3",  
            "20"=>"4",  
            "21"=>"4",  
            "22"=>"4",  
            "23"=>"4",  
            "24"=>"4",
            "25"=>"5",
            "26"=>"Es base fundamental."
        }.to_json
    },{
        qcd_id: 102,
        group: true,
        answer: {
            "1"=>"me gusta la clase pero me choca como el profesor lleva acabo algunas actividades", 
            "2"=>"4", 
            "3"=>"2", 
            "4"=>"3", 
            "5"=>"2", 
            "6"=>"1",
            "13"=>"Entre 3,95 y 5,00", 
            "14"=>"No", 
            "15"=>"3", 
            "16"=>"3", 
            "17"=>"3",  
            "18"=>"3",  
            "19"=>"2",  
            "20"=>"3",  
            "21"=>"2",  
            "22"=>"3",  
            "23"=>"2",  
            "24"=>"2",
            "25"=>"5",
            "26"=>"por que estoy estudiando comunicación eso es obvio y lógico y ademas quiero ser cronista, esta pregunta es muy estupida"
        }.to_json
    },{
        qcd_id: 102,
        group: true,
        answer: {
            "1"=>"Es un gusto dar la clase", 
            "2"=>"4", 
            "3"=>"3", 
            "4"=>"3", 
            "5"=>"3", 
            "6"=>"3",
            "13"=>"Entre 3,25 y 3,94", 
            "14"=>"No", 
            "15"=>"2", 
            "16"=>"3", 
            "17"=>"2",  
            "18"=>"4",  
            "19"=>"4",  
            "20"=>"4",  
            "21"=>"2",  
            "22"=>"2",  
            "23"=>"3",  
            "24"=>"4",
            "25"=>"5",
            "26"=>"Creo que la asignatura es fundamental para poder ser Comunicadores completos "
        }.to_json
    },{
        qcd_id: 102,
        group: true,
        answer: {
            "1"=> "Regular",
            "2"=>"3", 
            "3"=>"2", 
            "4"=>"2", 
            "5"=>"3", 
            "6"=>"3",
            "13"=>"Entre 3,95 y 5,00", 
            "14"=>"No", 
            "15"=>"3", 
            "16"=>"3", 
            "17"=>"3",  
            "18"=>"2",  
            "19"=>"2",  
            "20"=>"3",  
            "21"=>"2",  
            "22"=>"2",  
            "23"=>"3",  
            "24"=>"3",
            "25"=>"5",
            "26"=>"Porque el saber escribir y desenvolverse en los diferentes géneros periodismos es de suma importancia para el crecimiento profesional, es la base, el primer pilar para ser un periodista "
        }.to_json
    },{
        qcd_id: 102,
        group: true,
        answer: {
            "1"=>"Muy satisfecha.", 
            "2"=>"5", 
            "3"=>"3", 
            "4"=>"2", 
            "5"=>"3", 
            "6"=>"2",
            "13"=>"Entre 3,95 y 5,00", 
            "14"=>"No", 
            "15"=>"3", 
            "16"=>"4", 
            "17"=>"4",  
            "18"=>"4",  
            "19"=>"4",  
            "20"=>"4",  
            "21"=>"4",  
            "22"=>"4",  
            "23"=>"4",  
            "24"=>"4",
            "25"=>"5",
            "26"=>"El periodismo es uno de los fuertes del programa de Comunicación Social y Periodismo; por esta razón, considero que es pertinente que un comunicador social y periodista de la Universidad del Norte sea capaz de responder a todos los retos al momento de aplicar su aprendizaje en el campo del periodismo."
        }.to_json
    },{
        qcd_id: 102,
        group: true,
        answer: {
            "1"=>"Me ha llamado la atención conocer el tema pero no he aprendido el manejo del mismo.", 
            "2"=>"3", 
            "3"=>"2", 
            "4"=>"3", 
            "5"=>"3", 
            "6"=>"3",
            "13"=>"Entre 3,95 y 5,00", 
            "14"=>"No", 
            "15"=>"3", 
            "16"=>"4", 
            "17"=>"2",  
            "18"=>"4",  
            "19"=>"2",  
            "20"=>"4",  
            "21"=>"4",  
            "22"=>"3",  
            "23"=>"3",  
            "24"=>"4",
            "25"=>"5",
            "26"=>"La puedo desempeñar en cualquier ámbito laboral"
        }.to_json
    },{
        qcd_id: 102,
        group: true,
        answer: {
            "1"=>"Regular", 
            "2"=>"3", 
            "3"=>"2", 
            "4"=>"2", 
            "5"=>"2", 
            "6"=>"2",
            "13"=>"Entre 3,25 y 3,94", 
            "14"=>"No", 
            "15"=>"3", 
            "16"=>"3", 
            "17"=>"3",  
            "18"=>"3",  
            "19"=>"2",  
            "20"=>"1",  
            "21"=>"1",  
            "22"=>"3",  
            "23"=>"4",  
            "24"=>"2",
            "25"=>"5",
            "26"=>"Es importante saber escribir, expresar, e informar lo que sucede en nuestro entorno. "
        }.to_json
    },{
        qcd_id: 102,
        group: true,
        answer: {
            "1"=>"Ya no me gusta esta materia", 
            "2"=>"2", 
            "3"=>"2", 
            "4"=>"2", 
            "5"=>"2", 
            "6"=>"2",
            "13"=>"Entre 3,25 y 3,94", 
            "14"=>"No", 
            "15"=>"4", 
            "16"=>"4", 
            "17"=>"4",  
            "18"=>"4",  
            "19"=>"2",  
            "20"=>"3",  
            "21"=>"2",  
            "22"=>"3",  
            "23"=>"3",  
            "24"=>"3",
            "25"=>"5",
            "26"=>"Un periodista debe crear su propio estilo desde que inicia para proyectarlo como posteriormente como profesional."
        }.to_json
    },{
        qcd_id: 102,
        group: true,
        answer: {
            "1"=>"Muy satisfecha", 
            "2"=>"4", 
            "3"=>"3", 
            "4"=>"3", 
            "5"=>"3", 
            "6"=>"3",
            "13"=>"Entre 3,95 y 5,00", 
            "14"=>"No", 
            "15"=>"4", 
            "16"=>"4", 
            "17"=>"4",  
            "18"=>"4",  
            "19"=>"4",  
            "20"=>"4",  
            "21"=>"4",  
            "22"=>"4",  
            "23"=>"4",  
            "24"=>"4",
            "25"=>"5",
            "26"=>"porque estudio comunicación social y periodismo por lo tanto es fundamental en la carrera que elegí."
        }.to_json
    },{
        qcd_id: 102,
        group: true,
        answer: {
            "1"=>"He recibido más de lo que esperé de esta clase", 
            "2"=>"5", 
            "3"=>"3", 
            "4"=>"2", 
            "5"=>"3", 
            "6"=>"3",
            "13"=>"Entre 3,95 y 5,00", 
            "14"=>"No", 
            "15"=>"4", 
            "16"=>"3", 
            "17"=>"4",  
            "18"=>"4",  
            "19"=>"4",  
            "20"=>"4",  
            "21"=>"4",  
            "22"=>"4",  
            "23"=>"4",  
            "24"=>"4",
            "25"=>"5",
            "26"=>"Es una asignatura básica que me proporciona herramientas para un desempeño profesional futuro"
        }.to_json
    },{
        qcd_id: 102,
        group: true,
        answer: {
            "1"=>"Siento que he avanzado de manera positiva en el proceso de escritura", 
            "2"=>"4", 
            "3"=>"3", 
            "4"=>"2", 
            "5"=>"1", 
            "6"=>"3",
            "13"=>"Entre 3,25 y 3,94", 
            "14"=>"No", 
            "15"=>"3", 
            "16"=>"4", 
            "17"=>"4",  
            "18"=>"4",  
            "19"=>"4",  
            "20"=>"3",  
            "21"=>"3",  
            "22"=>"2",  
            "23"=>"4",  
            "24"=>"4",
            "25"=>"5",
            "26"=>"Por que es una rama importante en la comunicación social y considero importante la buena redacción"
        }.to_json
    },{
        qcd_id: 102,
        group: true,
        answer: {
            "1"=>"he aprendido mucho", 
            "2"=>"5", 
            "3"=>"0", 
            "4"=>"0", 
            "5"=>"0", 
            "6"=>"0",
            "13"=>"Entre 3,95 y 5,00", 
            "14"=>"No", 
            "15"=>"2", 
            "16"=>"2", 
            "17"=>"2",  
            "18"=>"2",  
            "19"=>"2",  
            "20"=>"2",  
            "21"=>"2",  
            "22"=>"2",  
            "23"=>"2",  
            "24"=>"2",
            "25"=>"5",
            "26"=>"porque es una de las razones por las cuales puedo mostrar diferentes realidades"
        }.to_json
    },{
        qcd_id: 102,
        group: true,
        answer: {
            "1"=>"básica", 
            "2"=>"3", 
            "3"=>"1", 
            "4"=>"2", 
            "5"=>"2", 
            "6"=>"2",
            "13"=>"Entre 3,95 y 5,00", 
            "14"=>"No", 
            "15"=>"2", 
            "16"=>"2", 
            "17"=>"2",  
            "18"=>"3",  
            "19"=>"3",  
            "20"=>"4",  
            "21"=>"3",  
            "22"=>"4",  
            "23"=>"4",  
            "24"=>"3",
            "25"=>"5",
            "26"=>"El periodismo es la herramienta básica de todo comunicador   con la cual retrata  el mundo que nos rodea."
        }.to_json
    },{
        qcd_id: 102,
        group: true,
        answer: {
            "1"=>"regular", 
            "2"=>"2", 
            "3"=>"2", 
            "4"=>"2", 
            "5"=>"2", 
            "6"=>"2",
            "13"=>"Entre 3,95 y 5,00", 
            "14"=>"Si", 
            "15"=>"3", 
            "16"=>"2", 
            "17"=>"2",  
            "18"=>"3",  
            "19"=>"2",  
            "20"=>"2",  
            "21"=>"1",  
            "22"=>"2",  
            "23"=>"2",  
            "24"=>"2",
            "25"=>"5",
            "26"=>"Es muy importante ya que nos permite capacitarnos al contar historias  y tener una mejor redacción que nos sirve para cualquier trabajo."
        }.to_json
    },{
        qcd_id: 102,
        group: true,
        answer: {
            "1"=>"En general me siento muy satisfecho/a.", 
            "2"=>"4", 
            "3"=>"3", 
            "4"=>"2", 
            "5"=>"3", 
            "6"=>"3",
            "13"=>"Entre 3,95 y 5,00", 
            "14"=>"No", 
            "15"=>"3", 
            "16"=>"3", 
            "17"=>"3",  
            "18"=>"3",  
            "19"=>"4",  
            "20"=>"4",  
            "21"=>"4",  
            "22"=>"3",  
            "23"=>"4",  
            "24"=>"4",
            "25"=>"5",
            "26"=>"Porque independientemente de la rama de la comunicación por la que uno termine inclinándose, tanto el conocimiento de la actualidad como la capacidad de redacción son indispensables."
        }.to_json
    }
    ])
	

